"""add order reference to inventory movements

Revision ID: 0ef34b2215fe
Revises: c8d89e16d2f9
Create Date: 2026-09-03 17:25:48.103922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef34b2215fe'
down_revision: Union[str, Sequence[str], None] = 'c8d89e16d2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('order_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'order_id')
    # ### end Alembic commands ###
