"""add razorpay payment ids

Revision ID: b9c0246d5b2c
Revises: 6c47b4efa3c0
Create Date: 2026-09-10 22:59:06.550408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c0246d5b2c'
down_revision: Union[str, Sequence[str], None] = '6c47b4efa3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'payments', ['razorpay_order_id'])
    op.create_unique_constraint(None, 'payments', ['razorpay_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_order_id')
    # ### end Alembic commands ###
